workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 120
    environment:
      java: 11
    triggering:
      events:
        - push
    scripts:
      - name: Build APK
        script: |
          mkdir -p android/app/src/main/assets/www
          cp index.html android/app/src/main/assets/www/
          mkdir -p android/app/src/main/java/com/stravamin/app
          mkdir -p android/app/src/main
          
          cat > android/build.gradle << 'EOF'
          buildscript {
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath 'com.android.tools.build:gradle:7.4.0'
              }
          }
          EOF
          
          cat > android/settings.gradle << 'EOF'
          pluginManagement {
              repositories {
                  gradlePluginPortal()
                  google()
                  mavenCentral()
              }
          }
          dependencyResolutionManagement {
              repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
              repositories {
                  google()
                  mavenCentral()
              }
          }
          rootProject.name = "StravaMin"
          include ':app'
          EOF
          
          cat > android/app/build.gradle << 'EOF'
          plugins {
              id 'com.android.application'
          }
          android {
              namespace 'com.stravamin.app'
              compileSdk 33
              defaultConfig {
                  applicationId 'com.stravamin.app'
                  minSdk 21
                  targetSdk 33
                  versionCode 1
                  versionName '1.0.0'
              }
              buildTypes {
                  debug {
                      debuggable true
                  }
              }
          }
          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
          }
          EOF
          
          cat > android/app/src/main/AndroidManifest.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.stravamin.app">
              <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
              <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
              <uses-permission android:name="android.permission.INTERNET" />
              <application
                  android:allowBackup="true"
                  android:label="StravaMin"
                  android:theme="@style/Theme.AppCompat.Light">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
          
          cat > android/app/src/main/java/com/stravamin/app/MainActivity.java << 'EOF'
          package com.stravamin.app;
          import android.os.Bundle;
          import android.webkit.WebView;
          import android.webkit.WebViewClient;
          import androidx.appcompat.app.AppCompatActivity;
          public class MainActivity extends AppCompatActivity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  WebView webView = new WebView(this);
                  setContentView(webView);
                  webView.setWebViewClient(new WebViewClient());
                  webView.getSettings().setJavaScriptEnabled(true);
                  webView.getSettings().setDomStorageEnabled(true);
                  webView.getSettings().setGeolocationEnabled(true);
                  webView.loadUrl("file:///android_asset/www/index.html");
              }
          }
          EOF
          
          cd android
          gradle wrapper --gradle-version 7.6
          ./gradlew assembleDebug
          
      - name: Copy APK
        script: |
          mkdir -p $CM_BUILD_DIR/artifacts
          cp android/app/build/outputs/apk/debug/app-debug.apk $CM_BUILD_DIR/artifacts/StravaMin.apk
          
    artifacts:
      - $CM_BUILD_DIR/artifacts/StravaMin.apk
