workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 120
    environment:
      node: 16
      java: 11
    triggering:
      events:
        - push
    scripts:
      - name: Install Node dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli@latest
      - name: Initialize Capacitor
        script: |
          npx cap init stravamin com.stravamin.app --web-dir build
      - name: Add Android
        script: |
          npx cap add android || true
      - name: Sync Android
        script: |
          npx cap sync android || true
      - name: Build Android APK
        script: |
          cd android && chmod +x ./gradlew && ./gradlew assembleDebug
      - name: Copy APK
        script: |
          cp android/app/build/outputs/apk/debug/app-debug.apk "$CM_BUILD_DIR/app-debug.apk" || true
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
