workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 120
    environment:
      node: 16
      java: 11
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web
        script: |
          npm run build
      - name: Add Android platform
        script: |
          npm install -g @capacitor/cli
          npx cap add android
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
      - name: Copy APK
        script: |
          cp android/app/build/outputs/apk/debug/app-debug.apk "$CM_BUILD_DIR/app-debug.apk"
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
